language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - pip install --user codecov
  - npm install
  - mongo subscribers-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - echo 'MONGO_URL=mongodb://travis:test@localhost/subscribers-test' >> .env.test
script:
  - npm run test
after_success:
  - codecov --file coverage/lcov.info --disable search
notifications:
  email: false
